%YAML:1.0
Settings:
  #Program modes:
  #   INTRINSIC  — calculates intrinsics parameters and  undistorts images
  #   STEREO     — calculates extrinsic stereo paramaters and rectifies images
  #   PREVIEW    — detects pattern on live feed, previewing detection and undistortion
  Mode: PREVIEW
  #Three supported calibration patterns: CHESSBOARD, ARUCO_SINGLE, ARUCO_BOX
  Calibration_Pattern: ARUCO_SINGLE

  #Number of inner corners per chessboard row and column
  ChessboardSize_Width: 12
  ChessboardSize_Height: 17
  #The size of a square in some user defined metric system (pixel, millimeter, etc.)
  SquareSize: .025

  #Filename for image list
  imageList_Filename: "0"
  #Filename for aruco config files
  arucoConfigList_Filename: "../input/configLists/singleConfig.xml"
  #Intrinsic input filename. These intrinsics can be used as an initial estimate
  #for intrinsic calibration, as fixed intrinsics for stereo calibration, or to
  #preview undistortion in preview mode
  #Leave at "0" to calculate new intrinsics
  intrinsicInput_Filename: "../output/intrinsics/webcamIntrinsics.yml"

  #File to write results of inrinsic calibration
  IntrinsicOutput_Filename: "0"
  #File to write extrinsics of stereo calibration
  ExtrinsicOutput_Filename: "0"

  #LEAVE THESE SETTINGS AT "0" TO NOT SAVE IMAGES
  #Path at which to save undistorted images
  UndistortedImages_Path: "0"
  #Path at which to save rectified images
  RectifiedImages_Path: "0"
  #Path at which to save images with detected patterns drawn
  DetectedImages_Path: "0"

  #A string of five digits (0 or 1) that controls which distortion coefficients
  #among K1-K5 will be fixed (1 = fixed)
  Calibrate_FixDistCoeffs: "00111"
  #A non-zero input will fix the aspect ratio
  Calibrate_FixAspectRatio: 0
  #Assume zero tangential distortion
  Calibrate_AssumeZeroTangentialDistortion: 0
  #Fix the principal point at the center
  Calibrate_FixPrincipalPointAtTheCenter: 0

  #Show undistorted images after intrinsic calibration
  Show_UndistortedImages: 0
  #Show rectified images after stereo calibration
  Show_RectifiedImages: 0
  #Draw each marker with its 3D coordinate. If false, IDs will be printed
  Show_ArucoMarkerCoordinates: 1
  #Wait until a key is pressed to show the next detected image
  Wait_NextDetectedImage: 0

  #ID for live preview camera. Generally "0" is built in webcam
  LivePreviewCameraID: "0"
